// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function Connect():Promise<desktop.StatusResponse>;

export function Disconnect():Promise<desktop.StatusResponse>;

export function GetRegistry():Promise<desktop.RegistryResponse>;

export function GetSkipQuitModal():Promise<boolean>;

export function GetStatus():Promise<desktop.StatusResponse>;

export function Quit():Promise<void>;

export function SelectCountry(arg1:string):Promise<desktop.StatusResponse>;

export function SetSkipQuitModal(arg1:boolean):Promise<void>;
