// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['desktop']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['desktop']['App']['Disconnect']();
}

export function GetRegistry() {
  return window['go']['desktop']['App']['GetRegistry']();
}

export function GetSkipQuitModal() {
  return window['go']['desktop']['App']['GetSkipQuitModal']();
}

export function GetStatus() {
  return window['go']['desktop']['App']['GetStatus']();
}

export function OnBeforeClose(arg1) {
  return window['go']['desktop']['App']['OnBeforeClose'](arg1);
}

export function Quit() {
  return window['go']['desktop']['App']['Quit']();
}

export function SelectCountry(arg1) {
  return window['go']['desktop']['App']['SelectCountry'](arg1);
}

export function SetSkipQuitModal(arg1) {
  return window['go']['desktop']['App']['SetSkipQuitModal'](arg1);
}
