//go:build linux

package dns

import (
	"context"
	"fmt"
	"net"
	"os"
	"os/exec"
	"strings"
)

// CheckCurrentResolver returns the current system DNS resolver address
// by reading resolv.conf or using resolvectl.
func CheckCurrentResolver(ctx context.Context) (string, error) {
	// Try resolvectl first.
	if out, err := exec.CommandContext(ctx, "resolvectl", "dns").CombinedOutput(); err == nil {
		lines := strings.Split(string(out), "\n")
		for _, line := range lines {
			trimmed := strings.TrimSpace(line)
			if strings.HasPrefix(trimmed, "Link") {
				parts := strings.Fields(trimmed)
				for _, part := range parts {
					if isIPAddr(part) {
						return part, nil
					}
				}
			}
		}
	}

	// Fallback to resolv.conf.
	content, err := os.ReadFile(resolvConfPath)
	if err != nil {
		return "", fmt.Errorf("dns: check resolver: %w", err)
	}

	lines := strings.Split(string(content), "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "nameserver") {
			parts := strings.Fields(trimmed)
			if len(parts) >= 2 {
				return parts[1], nil
			}
		}
	}

	return "", fmt.Errorf("dns: check resolver: no nameserver found in resolv.conf")
}

// ForceResolver sets the system DNS resolver without saving the original value.
// Used by the watchdog for corrections.
func ForceResolver(ctx context.Context, addr string) error {
	// Try resolvectl first.
	if _, err := exec.CommandContext(ctx, "which", "resolvectl").CombinedOutput(); err == nil {
		interfaces := discoverInterfaces(ctx)
		for _, iface := range interfaces {
			if _, err := exec.CommandContext(ctx, "resolvectl", "dns", iface, addr).CombinedOutput(); err != nil {
				return fmt.Errorf("dns: force resolver for %q: %w", iface, err)
			}
		}
		return nil
	}

	// Fallback to resolv.conf.
	content := fmt.Sprintf("# Generated by Le Voile VPN\nnameserver %s\n", addr)
	perm := os.FileMode(0644)
	if info, err := os.Stat(resolvConfPath); err == nil {
		perm = info.Mode().Perm()
	}
	if err := os.WriteFile(resolvConfPath, []byte(content), perm); err != nil {
		return fmt.Errorf("dns: force resolver: %w", err)
	}

	return nil
}

// discoverInterfaces finds active interfaces via resolvectl output.
func discoverInterfaces(ctx context.Context) []string {
	out, err := exec.CommandContext(ctx, "resolvectl", "dns").CombinedOutput()
	if err != nil {
		return []string{"eth0"}
	}
	interfaces := parseAllResolvectlInterfaces(string(out))
	if len(interfaces) == 0 {
		return []string{"eth0"}
	}
	return interfaces
}

func isIPAddr(s string) bool {
	return net.ParseIP(s) != nil
}
