//go:build linux

package dns

import (
	"context"
	"fmt"
	"os"
	"strings"
	"sync"
)

const resolvConfPath = "/etc/resolv.conf"
const resolvConfBackup = "/etc/resolv.conf.levoile.bak"

// linuxManager implements DNSManager using resolvectl or resolv.conf on Linux.
type linuxManager struct {
	originalDNS   string // original resolv.conf content or resolvectl DNS output
	useResolvectl bool
	mu            sync.Mutex
	run           commandRunner
}

// NewManager creates a Linux-specific DNS manager.
func NewManager() DNSManager {
	return newManagerWithRunner(defaultRunner)
}

// newManagerWithRunner creates a Linux DNS manager with a custom command runner (for testing).
func newManagerWithRunner(run commandRunner) DNSManager {
	m := &linuxManager{run: run}
	m.useResolvectl = m.hasResolvectl()
	return m
}

// hasResolvectl checks if resolvectl is available on the system.
func (m *linuxManager) hasResolvectl() bool {
	_, err := m.run(context.Background(), "which", "resolvectl")
	return err == nil
}

// SetResolver modifies the DNS resolver to point to addr.
func (m *linuxManager) SetResolver(ctx context.Context, addr string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.useResolvectl {
		return m.setResolverResolvectl(ctx, addr)
	}
	return m.setResolverResolvConf(ctx, addr)
}

// RestoreResolver restores the DNS resolver to its original value.
func (m *linuxManager) RestoreResolver(ctx context.Context) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.originalDNS == "" {
		return nil
	}

	if m.useResolvectl {
		return m.restoreResolvectl(ctx)
	}
	return m.restoreResolvConf()
}

// OriginalResolver returns the saved original DNS configuration.
func (m *linuxManager) OriginalResolver() string {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.originalDNS
}

// --- resolvectl implementation ---

func (m *linuxManager) setResolverResolvectl(ctx context.Context, addr string) error {
	// Save current DNS for all interfaces
	out, err := m.run(ctx, "resolvectl", "dns")
	if err != nil {
		return fmt.Errorf("dns: set resolver: get current dns: %w", err)
	}
	m.originalDNS = strings.TrimSpace(string(out))

	// Parse ALL interfaces from resolvectl output
	interfaces := parseAllResolvectlInterfaces(string(out))
	if len(interfaces) == 0 {
		interfaces = []string{"eth0"} // fallback
	}

	// Modify DNS on ALL interfaces
	for _, iface := range interfaces {
		out, err = m.run(ctx, "resolvectl", "dns", iface, addr)
		if err != nil {
			return fmt.Errorf("dns: set resolver: resolvectl for %q: %s: %w", iface, string(out), ErrSetResolverFailed)
		}
	}

	return nil
}

func (m *linuxManager) restoreResolvectl(ctx context.Context) error {
	// Revert ALL interfaces from saved state
	interfaces := parseAllResolvectlInterfaces(m.originalDNS)
	if len(interfaces) == 0 {
		interfaces = []string{"eth0"}
	}

	var lastErr error
	for _, iface := range interfaces {
		out, err := m.run(ctx, "resolvectl", "revert", iface)
		if err != nil {
			lastErr = fmt.Errorf("dns: restore resolver: resolvectl for %q: %s: %w", iface, string(out), ErrRestoreFailed)
		}
	}

	m.originalDNS = ""
	return lastErr
}

// parseAllResolvectlInterfaces extracts ALL interface names from resolvectl dns output.
// Format: "Link 2 (eth0): 192.168.1.1\nLink 3 (wlan0): 8.8.8.8"
func parseAllResolvectlInterfaces(output string) []string {
	var interfaces []string
	lines := strings.Split(output, "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "Link") {
			start := strings.Index(trimmed, "(")
			end := strings.Index(trimmed, ")")
			if start >= 0 && end > start {
				interfaces = append(interfaces, trimmed[start+1:end])
			}
		}
	}
	return interfaces
}

// --- resolv.conf implementation ---

func (m *linuxManager) setResolverResolvConf(ctx context.Context, addr string) error {
	// Read and save current resolv.conf
	content, err := os.ReadFile(resolvConfPath)
	if err != nil {
		return fmt.Errorf("dns: set resolver: read resolv.conf: %w", err)
	}
	m.originalDNS = string(content)

	// Preserve original file permissions
	perm := os.FileMode(0644)
	if info, err := os.Stat(resolvConfPath); err == nil {
		perm = info.Mode().Perm()
	}

	// Write backup with same permissions
	if err := os.WriteFile(resolvConfBackup, content, perm); err != nil {
		return fmt.Errorf("dns: set resolver: backup resolv.conf: %w", err)
	}

	// Write new resolv.conf with same permissions
	newContent := fmt.Sprintf("# Generated by Le Voile VPN\nnameserver %s\n", addr)
	if err := os.WriteFile(resolvConfPath, []byte(newContent), perm); err != nil {
		return fmt.Errorf("dns: set resolver: write resolv.conf: %w", ErrSetResolverFailed)
	}

	return nil
}

func (m *linuxManager) restoreResolvConf() error {
	// Preserve original file permissions
	perm := os.FileMode(0644)
	if info, err := os.Stat(resolvConfPath); err == nil {
		perm = info.Mode().Perm()
	}

	backup, err := os.ReadFile(resolvConfBackup)
	if err != nil {
		// Try to use saved original content
		if m.originalDNS != "" {
			if err := os.WriteFile(resolvConfPath, []byte(m.originalDNS), perm); err != nil {
				return fmt.Errorf("dns: restore resolver: write resolv.conf: %w", ErrRestoreFailed)
			}
			m.originalDNS = ""
			return nil
		}
		return fmt.Errorf("dns: restore resolver: read backup: %w", ErrRestoreFailed)
	}

	if err := os.WriteFile(resolvConfPath, backup, perm); err != nil {
		return fmt.Errorf("dns: restore resolver: write resolv.conf: %w", ErrRestoreFailed)
	}

	os.Remove(resolvConfBackup)
	m.originalDNS = ""
	return nil
}
