#!/usr/bin/env bash
# fetch-wintun.sh — télécharge wintun.dll 0.14.1 signée Microsoft, vérifie
# le SHA-256 de l'archive, extrait la DLL amd64 dans internal/tun/wintun/,
# et génère le fichier Go wintun_dll_windows.go avec la directive //go:embed.
#
# Usage :
#   bash scripts/fetch-wintun.sh           # amd64 (défaut)
#   WINTUN_ARCH=arm64 bash scripts/fetch-wintun.sh
#
# Doit tourner avant `go build` sur Windows, ou en CI. Idempotent : si la
# DLL existe déjà avec le bon hash, ne fait rien.

set -euo pipefail

WINTUN_VERSION="0.14.1"
WINTUN_ARCH="${WINTUN_ARCH:-amd64}"
WINTUN_URL="https://www.wintun.net/builds/wintun-${WINTUN_VERSION}.zip"
WINTUN_ZIP_SHA256="07c256185d6ee3652e09fa55c0b673e2624b565e02c4b9091c79ca7d2f24ef51"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TARGET_DIR="${REPO_ROOT}/internal/tun/wintun"
TARGET_DLL="${TARGET_DIR}/wintun.dll"
EMBED_GO="${REPO_ROOT}/internal/tun/wintun_dll_windows.go"

mkdir -p "${TARGET_DIR}"

# Vérifie si la DLL cible existe déjà avec un contenu non vide.
if [[ -s "${TARGET_DLL}" ]]; then
  echo "wintun.dll déjà présent dans ${TARGET_DIR} — skip download"
else
  TMP_ZIP="$(mktemp --suffix=.zip)"
  trap 'rm -f "${TMP_ZIP}"' EXIT

  echo "Téléchargement ${WINTUN_URL} …"
  curl -fsSL -o "${TMP_ZIP}" "${WINTUN_URL}"

  echo "Vérification SHA-256 archive…"
  ACTUAL="$(sha256sum "${TMP_ZIP}" | awk '{print $1}')"
  if [[ "${ACTUAL}" != "${WINTUN_ZIP_SHA256}" ]]; then
    echo "ERREUR : SHA-256 mismatch (got ${ACTUAL}, want ${WINTUN_ZIP_SHA256})" >&2
    exit 1
  fi

  echo "Extraction wintun/bin/${WINTUN_ARCH}/wintun.dll …"
  unzip -j -o "${TMP_ZIP}" "wintun/bin/${WINTUN_ARCH}/wintun.dll" -d "${TARGET_DIR}"

  if [[ ! -s "${TARGET_DLL}" ]]; then
    echo "ERREUR : wintun.dll non extraite" >&2
    exit 1
  fi
fi

# Génère le fichier Go qui injecte la DLL dans embeddedWintunDLL via embed.
cat > "${EMBED_GO}" <<'EOF'
//go:build windows

// Code generated by scripts/fetch-wintun.sh. DO NOT EDIT.
// Wintun DLL 0.14.1 signed by Microsoft — embedded at build time.

package tun

import _ "embed"

//go:embed wintun/wintun.dll
var wintunDLLBlob []byte

func init() { embeddedWintunDLL = wintunDLLBlob }
EOF

echo "OK : ${TARGET_DLL} + ${EMBED_GO} prêts pour go build"
